# Generated by Django 5.0.7 on 2024-08-13 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dogwalkingoffer",
            name="stakeholders",
        ),
        migrations.AddField(
            model_name="dogwalkingoffer",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="dogwalkingoffer",
            name="location",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="dogwalkingoffer",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
