# Generated by Django 5.0.7 on 2024-08-14 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_remove_dogwalkingoffer_stakeholders_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="dogwalkingoffer",
            name="stakeholders",
            field=models.ManyToManyField(
                blank=True, related_name="joined_offers", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="dogwalkingoffer",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="offers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
